<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { ArrowPathIcon, ChevronRightIcon, MagnifyingGlassIcon, PlusIcon, ShieldCheckIcon, ShieldExclamationIcon } from '@heroicons/vue/24/outline'
import { useAccountStore } from '@/domains/accounts/stores/accountStore'
import BlacklistFormPanel from '../components/BlacklistFormPanel.vue'
import { useBlacklistStore } from '../stores/blacklistStore'
import type { BlacklistInput } from '../types/blacklist'

const accounts = useAccountStore(); const blacklists = useBlacklistStore(); const panel = ref(false)
const canManage = computed(() => accounts.selected?.permissions.can_manage_call_routing ?? false)
const activeCount = computed(() => blacklists.records.filter((record) => record.is_active).length)
watch(() => accounts.selectedId, (id) => { panel.value = false; blacklists.reset(); if (id) void blacklists.load(id) }, { immediate: true })
async function open(id?: string): Promise<void> { if (!accounts.selectedId) return; await blacklists.prepare(accounts.selectedId, id); panel.value = true }
async function save(input: BlacklistInput): Promise<void> { if (accounts.selectedId && await blacklists.save(accounts.selectedId, input)) panel.value = false }
async function remove(): Promise<void> { if (accounts.selectedId && await blacklists.remove(accounts.selectedId)) panel.value = false }
</script>

<template>
  <section class="border-b border-slate-200/80 bg-white px-4 py-5 sm:px-6 lg:px-8"><div class="mx-auto flex max-w-[1500px] items-center gap-4"><div><p class="mb-1 text-[11px] text-slate-400">GridPBX / Security</p><h1 class="text-xl font-semibold text-slate-800">Blacklists</h1><p class="mt-1 text-xs text-slate-500">Protect inbound calls with reusable caller-number lists.</p></div><div class="ml-auto flex gap-2"><button v-if="canManage" :disabled="blacklists.synchronizing" class="inline-flex h-9 items-center gap-2 rounded-md border border-slate-200 bg-white px-4 text-xs font-semibold text-slate-600 disabled:opacity-40" @click="accounts.selectedId && blacklists.synchronize(accounts.selectedId)"><ArrowPathIcon class="size-4" :class="blacklists.synchronizing && 'animate-spin'" />Sync</button><button v-if="canManage" class="inline-flex h-9 items-center gap-2 rounded-md bg-brand-500 px-4 text-xs font-semibold text-white" @click="open()"><PlusIcon class="size-4" />New blacklist</button></div></div></section>
  <div class="mx-auto max-w-[1500px] p-4 sm:p-6 lg:p-8"><div class="mb-5 grid gap-4 sm:grid-cols-2"><article class="card-surface flex items-center gap-4 p-4"><span class="grid size-10 place-items-center rounded-md bg-slate-100 text-slate-600"><ShieldExclamationIcon class="size-5" /></span><div><p class="text-lg font-semibold text-slate-700">{{ blacklists.total }}</p><p class="text-[10px] font-semibold tracking-wide text-slate-400 uppercase">Caller lists</p></div></article><article class="card-surface flex items-center gap-4 p-4"><span class="grid size-10 place-items-center rounded-md bg-emerald-50 text-emerald-600"><ShieldCheckIcon class="size-5" /></span><div><p class="text-lg font-semibold text-slate-700">{{ activeCount }}</p><p class="text-[10px] font-semibold tracking-wide text-slate-400 uppercase">Active in this view</p></div></article></div>
    <div v-if="blacklists.error" class="mb-4 rounded-md border border-red-100 bg-red-50 p-4 text-xs text-danger">{{ blacklists.error }}</div><form class="mb-4 flex gap-3" @submit.prevent="accounts.selectedId && blacklists.load(accounts.selectedId)"><label class="relative min-w-0 flex-1"><MagnifyingGlassIcon class="absolute top-1/2 left-3 size-4 -translate-y-1/2 text-slate-400" /><input v-model="blacklists.search" type="search" placeholder="Search blacklists…" class="h-10 w-full rounded-md border border-slate-200 bg-white pr-3 pl-9 text-xs shadow-sm" /></label><button class="h-10 rounded-md border border-slate-200 bg-white px-5 text-xs font-semibold text-slate-600">Search</button></form>
    <div class="card-surface overflow-hidden"><table class="w-full text-left"><thead class="border-b border-slate-100 bg-slate-50/70 text-[10px] font-bold tracking-wider text-slate-400 uppercase"><tr><th class="px-5 py-3.5">Blacklist</th><th class="px-5 py-3.5">Numbers</th><th class="px-5 py-3.5">Anonymous</th><th class="px-5 py-3.5">Account status</th><th class="w-12"></th></tr></thead><tbody class="divide-y divide-slate-100 text-xs"><tr v-if="blacklists.loading"><td colspan="5" class="px-5 py-14 text-center text-slate-400">Loading blacklists…</td></tr><tr v-else-if="!blacklists.records.length"><td colspan="5" class="px-5 py-14 text-center text-slate-400">No blacklists are projected.</td></tr><tr v-for="record in blacklists.records" v-else :key="record.id" class="cursor-pointer hover:bg-slate-50" @click="open(record.id)"><td class="px-5 py-4 font-semibold text-slate-700">{{ record.name }}</td><td class="px-5 py-4 text-slate-500">{{ record.number_count ?? 0 }}</td><td class="px-5 py-4 text-slate-500">{{ record.should_block_anonymous ? 'Blocked' : 'Allowed' }}</td><td class="px-5 py-4"><span class="rounded-full px-2 py-1 text-[10px] font-semibold" :class="record.is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'">{{ record.is_active ? 'Active' : 'Inactive' }}</span></td><td><ChevronRightIcon class="size-4 text-slate-400" /></td></tr></tbody></table></div>
  </div>
  <BlacklistFormPanel v-if="panel" :record="blacklists.detail" :saving="blacklists.saving" :error="blacklists.mutationError" :field-errors="blacklists.fieldErrors" :can-manage="canManage" @close="panel = false" @save="save" @remove="remove" />
</template>
