import axios from 'axios'
import { defineStore } from 'pinia'
import { temporalRoutingApi } from '../api/temporalRoutingApi'
import type { TemporalOptions, TemporalRule, TemporalRuleInput, TemporalRuleSet, TemporalRuleSetInput } from '../types/temporalRouting'

const errorMessage = (error: unknown, fallback: string) => axios.isAxiosError(error) ? (error.response?.data?.message ?? fallback) : fallback
export const useTemporalRoutingStore = defineStore('temporal-routing', {
  state: () => ({ rules: [] as TemporalRule[], sets: [] as TemporalRuleSet[], ruleDetail: null as TemporalRule | null, setDetail: null as TemporalRuleSet | null, options: { rules: [] } as TemporalOptions, search: '', ruleTotal: 0, setTotal: 0, loading: false, saving: false, synchronizing: false, error: null as string | null, mutationError: null as string | null, fieldErrors: {} as Record<string, string[]> }),
  actions: {
    reset(): void { this.rules = []; this.sets = []; this.ruleDetail = null; this.setDetail = null; this.options = { rules: [] }; this.ruleTotal = 0; this.setTotal = 0; this.error = null; this.clearMutationError() },
    clearMutationError(): void { this.mutationError = null; this.fieldErrors = {} },
    capture(error: unknown, fallback: string): void { this.mutationError = errorMessage(error, fallback); this.fieldErrors = axios.isAxiosError(error) ? (error.response?.data?.errors ?? {}) : {} },
    async load(accountId: string): Promise<void> { this.loading = true; this.error = null; try { const [rules, sets] = await Promise.all([temporalRoutingApi.rules(accountId, this.search), temporalRoutingApi.sets(accountId, this.search)]); this.rules = rules.data; this.sets = sets.data; this.ruleTotal = rules.meta.total; this.setTotal = sets.meta.total } catch (error) { this.error = errorMessage(error, 'Unable to load temporal routing.') } finally { this.loading = false } },
    async prepareRule(accountId: string, id?: string): Promise<void> { this.loading = true; this.clearMutationError(); try { this.ruleDetail = id ? await temporalRoutingApi.rule(accountId, id) : null } catch (error) { this.error = errorMessage(error, 'Unable to prepare the temporal rule.') } finally { this.loading = false } },
    async prepareSet(accountId: string, id?: string): Promise<void> { this.loading = true; this.clearMutationError(); try { const [options, detail] = await Promise.all([temporalRoutingApi.options(accountId), id ? temporalRoutingApi.set(accountId, id) : Promise.resolve(null)]); this.options = options; this.setDetail = detail } catch (error) { this.error = errorMessage(error, 'Unable to prepare the rule set.') } finally { this.loading = false } },
    async saveRule(accountId: string, input: TemporalRuleInput): Promise<boolean> { this.saving = true; this.clearMutationError(); try { this.ruleDetail ? await temporalRoutingApi.updateRule(accountId, this.ruleDetail.id, input) : await temporalRoutingApi.createRule(accountId, input); await this.load(accountId); return true } catch (error) { this.capture(error, 'Unable to save temporal rule.'); return false } finally { this.saving = false } },
    async saveSet(accountId: string, input: TemporalRuleSetInput): Promise<boolean> { this.saving = true; this.clearMutationError(); try { this.setDetail ? await temporalRoutingApi.updateSet(accountId, this.setDetail.id, input) : await temporalRoutingApi.createSet(accountId, input); await this.load(accountId); return true } catch (error) { this.capture(error, 'Unable to save temporal rule set.'); return false } finally { this.saving = false } },
    async removeRule(accountId: string): Promise<boolean> { if (!this.ruleDetail) return false; this.saving = true; this.clearMutationError(); try { await temporalRoutingApi.removeRule(accountId, this.ruleDetail.id); this.ruleDetail = null; await this.load(accountId); return true } catch (error) { this.capture(error, 'Unable to delete temporal rule.'); return false } finally { this.saving = false } },
    async removeSet(accountId: string): Promise<boolean> { if (!this.setDetail) return false; this.saving = true; this.clearMutationError(); try { await temporalRoutingApi.removeSet(accountId, this.setDetail.id); this.setDetail = null; await this.load(accountId); return true } catch (error) { this.capture(error, 'Unable to delete temporal rule set.'); return false } finally { this.saving = false } },
    async synchronize(accountId: string): Promise<void> { this.synchronizing = true; this.error = null; try { let run = await temporalRoutingApi.startSync(accountId); for (let i = 0; i < 40 && ['queued', 'running'].includes(run.status); i += 1) { await new Promise((resolve) => window.setTimeout(resolve, 500)); run = await temporalRoutingApi.syncStatus(accountId, run.id) } if (run.status !== 'succeeded') throw new Error(run.error_message ?? 'Temporal routing sync did not finish.'); await this.load(accountId) } catch (error) { this.error = error instanceof Error ? error.message : errorMessage(error, 'Unable to synchronize temporal routing.') } finally { this.synchronizing = false } },
  },
})
