import type { Component } from 'vue'
import {
  ArrowPathIcon,
  ArrowPathRoundedSquareIcon,
  ArrowsRightLeftIcon,
  BellAlertIcon,
  BoltIcon,
  BuildingOfficeIcon,
  CalendarDaysIcon,
  ChatBubbleBottomCenterTextIcon,
  CircleStackIcon,
  ClockIcon,
  CodeBracketIcon,
  DevicePhoneMobileIcon,
  EnvelopeIcon,
  EyeIcon,
  ForwardIcon,
  GlobeAltIcon,
  HandRaisedIcon,
  HashtagIcon,
  IdentificationIcon,
  InboxArrowDownIcon,
  KeyIcon,
  LanguageIcon,
  LinkIcon,
  ListBulletIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  MicrophoneIcon,
  MusicalNoteIcon,
  NoSymbolIcon,
  PauseIcon,
  PhoneArrowDownLeftIcon,
  PhoneArrowUpRightIcon,
  PhoneIcon,
  PlayIcon,
  QueueListIcon,
  QuestionMarkCircleIcon,
  RectangleGroupIcon,
  ShieldCheckIcon,
  SignalIcon,
  SpeakerWaveIcon,
  Squares2X2Icon,
  StopIcon,
  UserGroupIcon,
  UserIcon,
  UsersIcon,
  VariableIcon,
} from '@heroicons/vue/24/outline'

const icons: Record<string, Component> = {
  user: UserIcon,
  device: DevicePhoneMobileIcon,
  callflow: ArrowPathRoundedSquareIcon,
  group: UserGroupIcon,
  ring_group: PhoneIcon,
  page_group: SpeakerWaveIcon,
  directory: BuildingOfficeIcon,
  menu: ListBulletIcon,
  conference: UsersIcon,
  acdc_member: QueueListIcon,
  acdc_queue: QueueListIcon,
  acdc_agent: IdentificationIcon,
  acdc_wait_time: ClockIcon,
  transfer: ArrowsRightLeftIcon,
  route_to_cid: IdentificationIcon,
  branch_bnumber: HashtagIcon,
  branch_variable: VariableIcon,
  offnet: GlobeAltIcon,
  resources: SignalIcon,
  play: MusicalNoteIcon,
  tts: ChatBubbleBottomCenterTextIcon,
  audio_macro: SpeakerWaveIcon,
  collect_dtmf: KeyIcon,
  send_dtmf: KeyIcon,
  flush_dtmf: ArrowPathIcon,
  dead_air: NoSymbolIcon,
  sleep: PauseIcon,
  language: LanguageIcon,
  record_call: MicrophoneIcon,
  record_caller: MicrophoneIcon,
  voicemail: InboxArrowDownIcon,
  faxbox: EnvelopeIcon,
  fax_detect: MagnifyingGlassIcon,
  receive_fax: InboxArrowDownIcon,
  missed_call_alert: BellAlertIcon,
  check_cid: MagnifyingGlassIcon,
  cidlistmatch: IdentificationIcon,
  dynamic_cid: IdentificationIcon,
  lookupcidname: MagnifyingGlassIcon,
  prepend_cid: IdentificationIcon,
  privacy: ShieldCheckIcon,
  set_cid: IdentificationIcon,
  set_alert_info: BellAlertIcon,
  nomorobo: ShieldCheckIcon,
  temporal_route: CalendarDaysIcon,
  manual_presence: HandRaisedIcon,
  do_not_disturb: NoSymbolIcon,
  call_forward: ForwardIcon,
  call_waiting: PhoneIcon,
  hotdesk: BuildingOfficeIcon,
  camping_feature: MapPinIcon,
  park: MapPinIcon,
  move: ArrowsRightLeftIcon,
  group_pickup: PhoneArrowDownLeftIcon,
  group_pickup_feature: PhoneArrowDownLeftIcon,
  ring_group_toggle: PhoneIcon,
  conference_feature: UsersIcon,
  intercom: SpeakerWaveIcon,
  after_bridge: LinkIcon,
  action: PlayIcon,
  disa: KeyIcon,
  eavesdrop: EyeIcon,
  eavesdrop_feature: EyeIcon,
  intercept: PhoneArrowDownLeftIcon,
  intercept_feature: PhoneArrowDownLeftIcon,
  pivot: CodeBracketIcon,
  webhook: GlobeAltIcon,
  response: PhoneArrowUpRightIcon,
  set: VariableIcon,
  set_variable: VariableIcon,
  set_variables: VariableIcon,
  edr: CircleStackIcon,
  hangup: StopIcon,
}

export function callflowActionIcon(module: string, unresolved = false): Component {
  return icons[module] ?? (unresolved ? QuestionMarkCircleIcon : Squares2X2Icon)
}

export const callflowEntryIcon = HashtagIcon
