import type { Component } from 'vue'
import {
  ArrowLeftStartOnRectangleIcon,
  ArrowPathIcon,
  ArrowRightStartOnRectangleIcon,
  ArrowsRightLeftIcon,
  BackspaceIcon,
  BellAlertIcon,
  BookOpenIcon,
  CalendarDaysIcon,
  ChatBubbleBottomCenterTextIcon,
  CircleStackIcon,
  ClockIcon,
  CloudArrowUpIcon,
  CodeBracketIcon,
  DevicePhoneMobileIcon,
  DocumentMagnifyingGlassIcon,
  EnvelopeIcon,
  EnvelopeOpenIcon,
  EyeIcon,
  EyeSlashIcon,
  ForwardIcon,
  GlobeAltIcon,
  HashtagIcon,
  IdentificationIcon,
  KeyIcon,
  LanguageIcon,
  LinkIcon,
  LightBulbIcon,
  ListBulletIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  MicrophoneIcon,
  MusicalNoteIcon,
  NoSymbolIcon,
  PauseIcon,
  PhoneArrowDownLeftIcon,
  PhoneArrowUpRightIcon,
  PhoneIcon,
  PhoneXMarkIcon,
  PlayIcon,
  PlusCircleIcon,
  PrinterIcon,
  QueueListIcon,
  QuestionMarkCircleIcon,
  ShareIcon,
  ShieldCheckIcon,
  SignalIcon,
  SpeakerWaveIcon,
  Squares2X2Icon,
  StopCircleIcon,
  UserMinusIcon,
  UserPlusIcon,
  UserGroupIcon,
  UserIcon,
  UsersIcon,
  VariableIcon,
} from '@heroicons/vue/24/outline'

const icons: Record<string, Component> = {
  user: UserIcon,
  device: DevicePhoneMobileIcon,
  callflow: ShareIcon,
  group: UserGroupIcon,
  ring_group: PhoneIcon,
  page_group: SpeakerWaveIcon,
  directory: BookOpenIcon,
  menu: ListBulletIcon,
  conference: UsersIcon,
  acdc_member: QueueListIcon,
  acdc_queue: QueueListIcon,
  acdc_agent: IdentificationIcon,
  acdc_wait_time: ClockIcon,
  transfer: ArrowsRightLeftIcon,
  route_to_cid: IdentificationIcon,
  branch_bnumber: HashtagIcon,
  branch_variable: VariableIcon,
  offnet: GlobeAltIcon,
  resources: SignalIcon,
  play: MusicalNoteIcon,
  tts: ChatBubbleBottomCenterTextIcon,
  audio_macro: SpeakerWaveIcon,
  collect_dtmf: KeyIcon,
  send_dtmf: KeyIcon,
  flush_dtmf: BackspaceIcon,
  dead_air: NoSymbolIcon,
  sleep: PauseIcon,
  language: LanguageIcon,
  record_call: MicrophoneIcon,
  record_caller: MicrophoneIcon,
  voicemail: EnvelopeIcon,
  faxbox: PrinterIcon,
  fax_detect: DocumentMagnifyingGlassIcon,
  receive_fax: PrinterIcon,
  missed_call_alert: BellAlertIcon,
  check_cid: MagnifyingGlassIcon,
  cidlistmatch: IdentificationIcon,
  dynamic_cid: IdentificationIcon,
  lookupcidname: MagnifyingGlassIcon,
  prepend_cid: IdentificationIcon,
  privacy: EyeSlashIcon,
  set_cid: IdentificationIcon,
  set_alert_info: BellAlertIcon,
  nomorobo: ShieldCheckIcon,
  temporal_route: CalendarDaysIcon,
  manual_presence: LightBulbIcon,
  do_not_disturb: NoSymbolIcon,
  call_forward: ForwardIcon,
  call_waiting: PhoneIcon,
  hotdesk: ArrowPathIcon,
  camping_feature: MapPinIcon,
  park: MapPinIcon,
  move: ArrowsRightLeftIcon,
  group_pickup: PhoneArrowDownLeftIcon,
  group_pickup_feature: PhoneArrowDownLeftIcon,
  ring_group_toggle: PhoneIcon,
  conference_feature: UsersIcon,
  intercom: SpeakerWaveIcon,
  after_bridge: LinkIcon,
  action: PlayIcon,
  disa: KeyIcon,
  eavesdrop: EyeIcon,
  eavesdrop_feature: EyeIcon,
  intercept: PhoneArrowDownLeftIcon,
  intercept_feature: PhoneArrowDownLeftIcon,
  pivot: CodeBracketIcon,
  webhook: CloudArrowUpIcon,
  response: PhoneArrowUpRightIcon,
  set: VariableIcon,
  set_variable: VariableIcon,
  set_variables: VariableIcon,
  edr: CircleStackIcon,
  hangup: PhoneXMarkIcon,
}

const actionIcons: Record<string, Component> = {
  'hotdesk:login': ArrowRightStartOnRectangleIcon,
  'hotdesk:logout': ArrowLeftStartOnRectangleIcon,
  'hotdesk:toggle': ArrowPathIcon,
  'prepend_cid:prepend': PlusCircleIcon,
  'prepend_cid:reset': ArrowPathIcon,
  'record_call:start': MicrophoneIcon,
  'record_call:stop': StopCircleIcon,
  'ring_group_toggle:login': UserPlusIcon,
  'ring_group_toggle:logout': UserMinusIcon,
  'acdc_queue:login': UserPlusIcon,
  'acdc_queue:logout': UserMinusIcon,
  'voicemail:check': EnvelopeOpenIcon,
}

export type CallflowActionIconOptions = {
  action?: string
  unresolved?: boolean
}

export function callflowActionIcon(
  module: string,
  options: CallflowActionIconOptions = {},
): Component {
  const variant = options.action ? actionIcons[`${module}:${options.action}`] : undefined

  return variant ?? icons[module] ?? (options.unresolved ? QuestionMarkCircleIcon : Squares2X2Icon)
}

export const callflowEntryIcon = HashtagIcon
