<script setup lang="ts">
import { computed, watch } from 'vue'
import { ArrowPathIcon, ChevronRightIcon, ClockIcon, MagnifyingGlassIcon, MicrophoneIcon } from '@heroicons/vue/24/outline'
import { useAccountStore } from '@/domains/accounts/stores/accountStore'
import RecordingDetailPanel from '../components/RecordingDetailPanel.vue'
import { useRecordingStore } from '../stores/recordingStore'

const accounts = useAccountStore(); const recordings = useRecordingStore()
const onPageDuration = computed(() => recordings.records.reduce((sum, record) => sum + record.duration_seconds, 0))
watch(() => accounts.selectedId, (id) => { recordings.reset(); if (id) void recordings.load(id) }, { immediate: true })
function apply(): void { if (accounts.selectedId) void recordings.load(accounts.selectedId, 1) }
function open(id: string): void { if (accounts.selectedId) void recordings.loadDetail(accounts.selectedId, id) }
const formatDuration = (seconds: number) => `${Math.floor(seconds / 60)}m ${seconds % 60}s`
</script>

<template>
  <section class="border-b border-slate-200/80 bg-white px-4 py-5 sm:px-6 lg:px-8"><div class="mx-auto flex max-w-[1500px] items-center gap-4"><div><p class="mb-1 text-[11px] text-slate-400">GridPBX / Calls</p><h1 class="text-xl font-semibold text-slate-800">Recordings</h1><p class="mt-1 text-xs text-slate-500">Metadata-only projection with protected playback and downloads.</p></div><button v-if="accounts.selected?.permissions.can_sync_call_detail_records" :disabled="recordings.synchronizing" class="ml-auto inline-flex h-9 items-center gap-2 rounded-md bg-brand-500 px-4 text-xs font-semibold text-white disabled:opacity-50" @click="accounts.selectedId && recordings.synchronize(accounts.selectedId)"><ArrowPathIcon class="size-4" :class="recordings.synchronizing && 'animate-spin'" />Sync last {{ recordings.importWindowDays }} days</button></div></section>
  <div class="mx-auto max-w-[1500px] p-4 sm:p-6 lg:p-8"><div class="mb-5 grid gap-4 sm:grid-cols-2"><article class="card-surface flex items-center gap-4 p-4"><span class="grid size-10 place-items-center rounded-md bg-brand-50 text-brand-600"><MicrophoneIcon class="size-5" /></span><div><p class="text-lg font-semibold text-slate-700">{{ recordings.total }}</p><p class="text-[10px] font-semibold tracking-wide text-slate-400 uppercase">Projected recordings</p></div></article><article class="card-surface flex items-center gap-4 p-4"><span class="grid size-10 place-items-center rounded-md bg-violet-50 text-violet-600"><ClockIcon class="size-5" /></span><div><p class="text-lg font-semibold text-slate-700">{{ formatDuration(onPageDuration) }}</p><p class="text-[10px] font-semibold tracking-wide text-slate-400 uppercase">Duration on page</p></div></article></div>
    <div v-if="recordings.error" class="mb-4 rounded-md border border-red-100 bg-red-50 p-4 text-xs text-danger">{{ recordings.error }}</div><form class="mb-4 grid gap-3 lg:grid-cols-[1fr_160px_160px_auto]" @submit.prevent="apply"><label class="relative"><MagnifyingGlassIcon class="absolute top-1/2 left-3 size-4 -translate-y-1/2 text-slate-400" /><input v-model="recordings.filters.search" type="search" placeholder="Search caller, callee, call, or name…" class="h-10 w-full rounded-md border border-slate-200 bg-white pr-3 pl-9 text-xs" /></label><select v-model="recordings.filters.direction" class="h-10 rounded-md border border-slate-200 bg-white px-3 text-xs"><option value="">All directions</option><option value="inbound">Inbound</option><option value="outbound">Outbound</option></select><select v-model="recordings.filters.has_audio" class="h-10 rounded-md border border-slate-200 bg-white px-3 text-xs"><option value="1">With audio</option><option value="">All records</option><option value="0">Without audio</option></select><button class="h-10 rounded-md border border-slate-200 bg-white px-5 text-xs font-semibold text-slate-600">Apply filters</button></form>
    <div class="card-surface overflow-hidden"><table class="w-full min-w-[820px] text-left"><thead class="border-b border-slate-100 bg-slate-50/70 text-[10px] font-bold tracking-wider text-slate-400 uppercase"><tr><th class="px-5 py-3.5">Started</th><th class="px-5 py-3.5">Direction</th><th class="px-5 py-3.5">Caller</th><th class="px-5 py-3.5">Callee</th><th class="px-5 py-3.5">Duration</th><th class="w-12"></th></tr></thead><tbody class="divide-y divide-slate-100 text-xs"><tr v-if="recordings.loading"><td colspan="6" class="px-5 py-14 text-center text-slate-400">Loading recordings…</td></tr><tr v-else-if="!recordings.records.length"><td colspan="6" class="px-5 py-14 text-center text-slate-400">No projected recordings match these filters.</td></tr><tr v-for="record in recordings.records" v-else :key="record.id" class="cursor-pointer hover:bg-slate-50" @click="open(record.id)"><td class="px-5 py-4 text-slate-500">{{ new Date(record.started_at).toLocaleString() }}</td><td class="px-5 py-4 text-slate-500 capitalize">{{ record.direction ?? 'Unknown' }}</td><td class="px-5 py-4"><p class="font-semibold text-slate-700">{{ record.caller.name ?? record.caller.number ?? 'Unknown' }}</p><p class="text-[10px] text-slate-400">{{ record.caller.number }}</p></td><td class="px-5 py-4"><p class="font-semibold text-slate-700">{{ record.callee.name ?? record.callee.number ?? 'Unknown' }}</p><p class="text-[10px] text-slate-400">{{ record.callee.number }}</p></td><td class="px-5 py-4 text-slate-500">{{ formatDuration(record.duration_seconds) }}</td><td><ChevronRightIcon class="size-4 text-slate-400" /></td></tr></tbody></table></div>
  </div>
  <RecordingDetailPanel v-if="recordings.detailLoading || recordings.detail || recordings.detailError" :record="recordings.detail" :loading="recordings.detailLoading" :audio-loading="recordings.audioLoading" :audio-url="recordings.audioUrl" :error="recordings.detailError" @close="recordings.closeDetail()" @download="accounts.selectedId && recordings.detail && recordings.downloadAudio(accounts.selectedId, recordings.detail.id)" />
</template>
