import axios from 'axios'
import { defineStore } from 'pinia'
import { faxApi } from '../api/faxApi'
import type { Fax, FaxBox, FaxBoxInput, FaxBoxOptions } from '../types/fax'

const emptyOptions: FaxBoxOptions = { owners: [] }
function message(error: unknown, fallback: string): string { return axios.isAxiosError(error) ? (error.response?.data?.message ?? fallback) : fallback }
export const useFaxStore = defineStore('faxes', {
  state: () => ({ boxes: [] as FaxBox[], messages: [] as Fax[], boxDetail: null as FaxBox | null, messageDetail: null as Fax | null, options: { ...emptyOptions }, search: '', folder: '', faxBoxId: '', page: 1, lastPage: 1, total: 0, loading: false, saving: false, synchronizing: false, downloading: false, error: null as string | null, mutationError: null as string | null, fieldErrors: {} as Record<string, string[]> }),
  actions: {
    reset(): void { this.boxes = []; this.messages = []; this.boxDetail = null; this.messageDetail = null; this.options = { ...emptyOptions }; this.total = 0; this.error = null; this.clearMutationError() },
    clearMutationError(): void { this.mutationError = null; this.fieldErrors = {} },
    capture(error: unknown, fallback: string): void { this.mutationError = message(error, fallback); this.fieldErrors = axios.isAxiosError(error) ? (error.response?.data?.errors ?? {}) : {} },
    async load(accountId: string, page = 1): Promise<void> { this.loading = true; this.error = null; try { const [boxes, messages] = await Promise.all([faxApi.boxes(accountId), faxApi.messages(accountId, this.search, this.folder, this.faxBoxId, page)]); this.boxes = boxes.data; this.messages = messages.data; this.page = messages.meta.current_page; this.lastPage = messages.meta.last_page; this.total = messages.meta.total } catch (error) { this.error = message(error, 'Unable to load fax data.') } finally { this.loading = false } },
    async prepareBox(accountId: string, id?: string): Promise<void> { this.loading = true; this.clearMutationError(); try { const [options, detail] = await Promise.all([faxApi.options(accountId), id ? faxApi.box(accountId, id) : Promise.resolve(null)]); this.options = options; this.boxDetail = detail } catch (error) { this.error = message(error, 'Unable to prepare the fax-box form.') } finally { this.loading = false } },
    async prepareMessage(accountId: string, id: string): Promise<void> { this.loading = true; try { this.messageDetail = await faxApi.message(accountId, id) } catch (error) { this.error = message(error, 'Unable to load the fax.') } finally { this.loading = false } },
    async saveBox(accountId: string, input: FaxBoxInput): Promise<boolean> { this.saving = true; this.clearMutationError(); try { if (this.boxDetail) await faxApi.updateBox(accountId, this.boxDetail.id, input); else await faxApi.createBox(accountId, input); await this.load(accountId); return true } catch (error) { this.capture(error, 'Unable to save fax box.'); return false } finally { this.saving = false } },
    async removeBox(accountId: string): Promise<boolean> { if (!this.boxDetail) return false; this.saving = true; this.clearMutationError(); try { await faxApi.removeBox(accountId, this.boxDetail.id); this.boxDetail = null; await this.load(accountId); return true } catch (error) { this.capture(error, 'Unable to delete fax box.'); return false } finally { this.saving = false } },
    async download(accountId: string): Promise<void> { if (!this.messageDetail) return; this.downloading = true; this.mutationError = null; try { const blob = await faxApi.document(accountId, this.messageDetail.id); const url = URL.createObjectURL(blob); const anchor = window.document.createElement('a'); anchor.href = url; anchor.download = `fax-${this.messageDetail.id}.${this.messageDetail.document_content_type === 'application/pdf' ? 'pdf' : 'tiff'}`; anchor.click(); URL.revokeObjectURL(url) } catch (error) { this.mutationError = message(error, 'Unable to download the fax document.') } finally { this.downloading = false } },
    async synchronize(accountId: string): Promise<void> { this.synchronizing = true; this.error = null; try { let run = await faxApi.startSync(accountId); for (let attempt = 0; attempt < 40 && ['queued', 'running'].includes(run.status); attempt += 1) { await new Promise((resolve) => window.setTimeout(resolve, 500)); run = await faxApi.syncStatus(accountId, run.id) } if (run.status !== 'succeeded') throw new Error(run.error_message ?? 'Fax sync did not finish.'); await this.load(accountId) } catch (error) { this.error = error instanceof Error ? error.message : message(error, 'Unable to synchronize faxes.') } finally { this.synchronizing = false } },
  },
})
