<?php

use App\Domains\Blacklists\Controllers\BlacklistController;
use App\Domains\Blacklists\Controllers\BlacklistSyncController;
use App\Domains\CallDetailRecords\Controllers\CallDetailRecordController;
use App\Domains\CallDetailRecords\Controllers\CallDetailRecordSyncController;
use App\Domains\CallerIdLists\Controllers\CallerIdListController;
use App\Domains\CallerIdLists\Controllers\CallerIdListSyncController;
use App\Domains\CallRouting\Controllers\CallflowController;
use App\Domains\Conferences\Controllers\ConferenceController;
use App\Domains\Conferences\Controllers\ConferenceSyncController;
use App\Domains\Devices\Controllers\DeviceController;
use App\Domains\Devices\Controllers\DeviceHotdeskController;
use App\Domains\Devices\Controllers\DeviceProvisioningController;
use App\Domains\Devices\Controllers\DeviceProvisioningEnrollmentController;
use App\Domains\Directories\Controllers\DirectoryController;
use App\Domains\Directories\Controllers\DirectorySyncController;
use App\Domains\Extensions\Controllers\ExtensionController;
use App\Domains\Extensions\Controllers\ExtensionDetailController;
use App\Domains\Extensions\Controllers\ExtensionRecoveryController;
use App\Domains\Faxes\Controllers\FaxBoxController;
use App\Domains\Faxes\Controllers\FaxController;
use App\Domains\Faxes\Controllers\FaxDocumentController;
use App\Domains\Faxes\Controllers\FaxSyncController;
use App\Domains\Groups\Controllers\GroupController;
use App\Domains\Groups\Controllers\GroupSyncController;
use App\Domains\IdentityAccess\Controllers\SessionController;
use App\Domains\LineKeys\Controllers\LineKeyController;
use App\Domains\Media\Controllers\MediaAudioController;
use App\Domains\Media\Controllers\MediaController;
use App\Domains\Media\Controllers\MediaSyncController;
use App\Domains\Media\Controllers\MusicOnHoldController;
use App\Domains\Menus\Controllers\MenuController;
use App\Domains\Menus\Controllers\MenuSyncController;
use App\Domains\Organizations\Controllers\AccountController;
use App\Domains\Organizations\Controllers\AccountSettingsOptionsController;
use App\Domains\Organizations\Controllers\AccountStatusController;
use App\Domains\PhoneNumbers\Controllers\PhoneNumberController;
use App\Domains\PhoneNumbers\Controllers\PhoneNumberSyncController;
use App\Domains\Queues\Controllers\AgentController;
use App\Domains\Queues\Controllers\QueueController;
use App\Domains\Queues\Controllers\QueueSyncController;
use App\Domains\Recordings\Controllers\RecordingAudioController;
use App\Domains\Recordings\Controllers\RecordingController;
use App\Domains\Recordings\Controllers\RecordingSyncController;
use App\Domains\Services\Controllers\ServiceOverviewController;
use App\Domains\Services\Controllers\ServiceSyncController;
use App\Domains\SwitchSynchronization\Controllers\ExtensionSyncController;
use App\Domains\TemporalRouting\Controllers\TemporalOperationalControlController;
use App\Domains\TemporalRouting\Controllers\TemporalRoutingSyncController;
use App\Domains\TemporalRouting\Controllers\TemporalRuleController;
use App\Domains\TemporalRouting\Controllers\TemporalRuleSetController;
use App\Domains\Voicemail\Controllers\VoicemailBoxController;
use App\Domains\Voicemail\Controllers\VoicemailGreetingController;
use App\Domains\Voicemail\Controllers\VoicemailMessageController;
use App\Support\Http\ApiResponse;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::get('/health', fn () => ApiResponse::data([
        'service' => 'grid-api',
        'status' => 'healthy',
        'timestamp' => now()->toIso8601String(),
    ]));

    Route::middleware('auth:sanctum')->group(function (): void {
        Route::get('/session', [SessionController::class, 'show']);
        Route::get('/accounts', AccountController::class);

        Route::prefix('accounts/{account}')->group(function (): void {
            Route::get('/', [AccountController::class, 'show']);
            Route::get('/settings-options', AccountSettingsOptionsController::class);
            Route::put('/', [AccountController::class, 'update']);
            Route::post('/sync', [AccountController::class, 'refresh']);
            Route::put('/status', [AccountStatusController::class, 'update']);
            Route::get('/extensions', ExtensionController::class);
            Route::get('/extensions/options', [ExtensionController::class, 'options']);
            Route::post('/extensions', [ExtensionController::class, 'store']);
            Route::get('/extensions/{extension}', ExtensionDetailController::class);
            Route::put('/extensions/{extension}', [ExtensionController::class, 'update']);
            Route::get('/extensions/{extension}/deletion-preview', [ExtensionController::class, 'deletionPreview']);
            Route::delete('/extensions/{extension}', [ExtensionController::class, 'destroy']);
            Route::get('/extension-recovery', [ExtensionRecoveryController::class, 'index']);
            Route::post('/extension-recovery/{operation}', [ExtensionRecoveryController::class, 'recover']);
            Route::get('/devices', [DeviceController::class, 'index']);
            Route::get('/devices/options', [DeviceController::class, 'options']);
            Route::post('/devices', [DeviceController::class, 'store']);
            Route::get('/devices/{device}', [DeviceController::class, 'show']);
            Route::put('/devices/{device}', [DeviceController::class, 'update']);
            Route::delete('/devices/{device}', [DeviceController::class, 'destroy']);
            Route::get('/devices/{device}/hotdesk-users', [DeviceHotdeskController::class, 'index']);
            Route::put('/devices/{device}/hotdesk-users/{extension}', [DeviceHotdeskController::class, 'store']);
            Route::delete('/devices/{device}/hotdesk-users/{extension}', [DeviceHotdeskController::class, 'destroy']);
            Route::post('/devices/{device}/provisioning-sync', DeviceProvisioningController::class);
            Route::get('/devices/{device}/provisioning-enrollment', [DeviceProvisioningEnrollmentController::class, 'show']);
            Route::post('/devices/{device}/provisioning-enrollment', [DeviceProvisioningEnrollmentController::class, 'store']);
            Route::delete('/devices/{device}/provisioning-enrollment', [DeviceProvisioningEnrollmentController::class, 'destroy']);
            Route::get('/line-keys', [LineKeyController::class, 'index']);
            Route::get('/devices/{device}/line-keys/preview', [LineKeyController::class, 'preview']);
            Route::put('/devices/{device}/line-keys', [LineKeyController::class, 'update']);
            Route::get('/directories', [DirectoryController::class, 'index']);
            Route::get('/directories/options', [DirectoryController::class, 'options']);
            Route::post('/directories', [DirectoryController::class, 'store']);
            Route::get('/directories/{directory}', [DirectoryController::class, 'show']);
            Route::put('/directories/{directory}', [DirectoryController::class, 'update']);
            Route::delete('/directories/{directory}', [DirectoryController::class, 'destroy']);
            Route::post('/sync/directories', [DirectorySyncController::class, 'store']);
            Route::get('/sync/directories/{run}', [DirectorySyncController::class, 'show']);
            Route::get('/groups', [GroupController::class, 'index']);
            Route::get('/groups/options', [GroupController::class, 'options']);
            Route::post('/groups', [GroupController::class, 'store']);
            Route::get('/groups/{group}', [GroupController::class, 'show']);
            Route::put('/groups/{group}', [GroupController::class, 'update']);
            Route::delete('/groups/{group}', [GroupController::class, 'destroy']);
            Route::post('/sync/groups', [GroupSyncController::class, 'store']);
            Route::get('/sync/groups/{run}', [GroupSyncController::class, 'show']);
            Route::get('/queues', [QueueController::class, 'index']);
            Route::get('/queues/options', [QueueController::class, 'options']);
            Route::post('/queues', [QueueController::class, 'store']);
            Route::get('/queues/{queue}', [QueueController::class, 'show']);
            Route::put('/queues/{queue}', [QueueController::class, 'update']);
            Route::delete('/queues/{queue}', [QueueController::class, 'destroy']);
            Route::get('/agents', [AgentController::class, 'index']);
            Route::get('/agents/{agent}/status', [AgentController::class, 'status']);
            Route::post('/agents/{agent}/status', [AgentController::class, 'updateStatus']);
            Route::post('/sync/queues', [QueueSyncController::class, 'store']);
            Route::get('/sync/queues/{run}', [QueueSyncController::class, 'show']);
            Route::get('/menus', [MenuController::class, 'index']);
            Route::get('/blacklists', [BlacklistController::class, 'index']);
            Route::post('/blacklists', [BlacklistController::class, 'store']);
            Route::get('/blacklists/{blacklist}', [BlacklistController::class, 'show']);
            Route::put('/blacklists/{blacklist}', [BlacklistController::class, 'update']);
            Route::delete('/blacklists/{blacklist}', [BlacklistController::class, 'destroy']);
            Route::post('/sync/blacklists', [BlacklistSyncController::class, 'store']);
            Route::get('/sync/blacklists/{run}', [BlacklistSyncController::class, 'show']);
            Route::get('/caller-id-lists', [CallerIdListController::class, 'index']);
            Route::post('/caller-id-lists', [CallerIdListController::class, 'store']);
            Route::get('/caller-id-lists/{callerIdList}', [CallerIdListController::class, 'show']);
            Route::put('/caller-id-lists/{callerIdList}', [CallerIdListController::class, 'update']);
            Route::delete('/caller-id-lists/{callerIdList}', [CallerIdListController::class, 'destroy']);
            Route::post('/sync/caller-id-lists', [CallerIdListSyncController::class, 'store']);
            Route::get('/sync/caller-id-lists/{run}', [CallerIdListSyncController::class, 'show']);
            Route::get('/menus/options', [MenuController::class, 'options']);
            Route::post('/menus', [MenuController::class, 'store']);
            Route::get('/menus/{menu}', [MenuController::class, 'show']);
            Route::put('/menus/{menu}', [MenuController::class, 'update']);
            Route::delete('/menus/{menu}', [MenuController::class, 'destroy']);
            Route::post('/sync/menus', [MenuSyncController::class, 'store']);
            Route::get('/sync/menus/{run}', [MenuSyncController::class, 'show']);
            Route::get('/temporal-rules', [TemporalRuleController::class, 'index']);
            Route::post('/temporal-rules', [TemporalRuleController::class, 'store']);
            Route::get('/temporal-rules/{rule}', [TemporalRuleController::class, 'show']);
            Route::put('/temporal-rules/{rule}', [TemporalRuleController::class, 'update']);
            Route::delete('/temporal-rules/{rule}', [TemporalRuleController::class, 'destroy']);
            Route::post('/temporal-rules/{rule}/commands', [TemporalOperationalControlController::class, 'rule']);
            Route::get('/temporal-rule-sets', [TemporalRuleSetController::class, 'index']);
            Route::get('/temporal-rule-sets/options', [TemporalRuleSetController::class, 'options']);
            Route::post('/temporal-rule-sets', [TemporalRuleSetController::class, 'store']);
            Route::get('/temporal-rule-sets/{set}', [TemporalRuleSetController::class, 'show']);
            Route::put('/temporal-rule-sets/{set}', [TemporalRuleSetController::class, 'update']);
            Route::delete('/temporal-rule-sets/{set}', [TemporalRuleSetController::class, 'destroy']);
            Route::post('/temporal-rule-sets/{set}/commands', [TemporalOperationalControlController::class, 'ruleSet']);
            Route::post('/sync/temporal-routing', [TemporalRoutingSyncController::class, 'store']);
            Route::get('/sync/temporal-routing/{run}', [TemporalRoutingSyncController::class, 'show']);
            Route::get('/phone-numbers', [PhoneNumberController::class, 'index']);
            Route::get('/phone-numbers/{phoneNumber}', [PhoneNumberController::class, 'show']);
            Route::get('/callflows', [CallflowController::class, 'index']);
            Route::get('/callflows/editor', [CallflowController::class, 'createOptions']);
            Route::post('/callflows', [CallflowController::class, 'store']);
            Route::get('/callflows/{callflow}/editor', [CallflowController::class, 'edit']);
            Route::get('/callflows/{callflow}', [CallflowController::class, 'show']);
            Route::put('/callflows/{callflow}', [CallflowController::class, 'update']);
            Route::patch('/callflows/{callflow}/tree', [CallflowController::class, 'moveNode']);
            Route::patch('/callflows/{callflow}/tree/order', [CallflowController::class, 'reorderNodes']);
            Route::post('/callflows/{callflow}/tree/nodes', [CallflowController::class, 'createNode']);
            Route::patch('/callflows/{callflow}/tree/nodes', [CallflowController::class, 'updateNode']);
            Route::post('/callflows/{callflow}/tree/inline-nodes', [CallflowController::class, 'createInlineNode']);
            Route::patch('/callflows/{callflow}/tree/inline-nodes', [CallflowController::class, 'updateInlineNode']);
            Route::delete('/callflows/{callflow}', [CallflowController::class, 'destroy']);
            Route::get('/call-detail-records', [CallDetailRecordController::class, 'index']);
            Route::get('/call-detail-records/{callDetailRecord}', [CallDetailRecordController::class, 'show']);
            Route::get('/recordings', [RecordingController::class, 'index']);
            Route::get('/recordings/{recording}', [RecordingController::class, 'show']);
            Route::get('/recordings/{recording}/audio', [RecordingAudioController::class, 'show']);
            Route::post('/sync/recordings', [RecordingSyncController::class, 'store']);
            Route::get('/sync/recordings/{run}', [RecordingSyncController::class, 'show']);
            Route::get('/conferences', [ConferenceController::class, 'index']);
            Route::get('/conferences/options', [ConferenceController::class, 'options']);
            Route::post('/conferences', [ConferenceController::class, 'store']);
            Route::get('/conferences/{conference}', [ConferenceController::class, 'show']);
            Route::put('/conferences/{conference}', [ConferenceController::class, 'update']);
            Route::delete('/conferences/{conference}', [ConferenceController::class, 'destroy']);
            Route::post('/sync/conferences', [ConferenceSyncController::class, 'store']);
            Route::get('/sync/conferences/{run}', [ConferenceSyncController::class, 'show']);
            Route::get('/fax-boxes', [FaxBoxController::class, 'index']);
            Route::get('/fax-boxes/options', [FaxBoxController::class, 'options']);
            Route::post('/fax-boxes', [FaxBoxController::class, 'store']);
            Route::get('/fax-boxes/{faxBox}', [FaxBoxController::class, 'show']);
            Route::put('/fax-boxes/{faxBox}', [FaxBoxController::class, 'update']);
            Route::delete('/fax-boxes/{faxBox}', [FaxBoxController::class, 'destroy']);
            Route::get('/faxes', [FaxController::class, 'index']);
            Route::get('/faxes/{fax}', [FaxController::class, 'show']);
            Route::get('/faxes/{fax}/document', [FaxDocumentController::class, 'show']);
            Route::post('/sync/faxes', [FaxSyncController::class, 'store']);
            Route::get('/sync/faxes/{run}', [FaxSyncController::class, 'show']);
            Route::get('/services', [ServiceOverviewController::class, 'show']);
            Route::post('/sync/services', [ServiceSyncController::class, 'store']);
            Route::get('/sync/services/{run}', [ServiceSyncController::class, 'show']);
            Route::get('/media', [MediaController::class, 'index']);
            Route::post('/media', [MediaController::class, 'store']);
            Route::get('/media/music-on-hold', [MusicOnHoldController::class, 'show']);
            Route::put('/media/music-on-hold', [MusicOnHoldController::class, 'update']);
            Route::get('/media/{media}', [MediaController::class, 'show']);
            Route::put('/media/{media}', [MediaController::class, 'update']);
            Route::delete('/media/{media}', [MediaController::class, 'destroy']);
            Route::get('/media/{media}/audio', [MediaAudioController::class, 'show']);
            Route::post('/media/{media}/audio', [MediaAudioController::class, 'store']);
            Route::post('/sync/media', [MediaSyncController::class, 'store']);
            Route::get('/sync/media/{run}', [MediaSyncController::class, 'show']);
            Route::post('/sync/call-detail-records', [CallDetailRecordSyncController::class, 'store']);
            Route::get('/sync/call-detail-records/{run}', [CallDetailRecordSyncController::class, 'show']);
            Route::post('/sync/phone-numbers', [PhoneNumberSyncController::class, 'store']);
            Route::get('/sync/phone-numbers/{run}', [PhoneNumberSyncController::class, 'show']);
            Route::get('/voicemail-boxes', [VoicemailBoxController::class, 'index']);
            Route::get('/voicemail-boxes/options', [VoicemailBoxController::class, 'options']);
            Route::post('/voicemail-boxes', [VoicemailBoxController::class, 'store']);
            Route::get('/voicemail-boxes/{voicemailBox}', [VoicemailBoxController::class, 'show']);
            Route::put('/voicemail-boxes/{voicemailBox}', [VoicemailBoxController::class, 'update']);
            Route::delete('/voicemail-boxes/{voicemailBox}', [VoicemailBoxController::class, 'destroy']);
            Route::get('/voicemail-boxes/{voicemailBox}/messages', [VoicemailMessageController::class, 'index']);
            Route::patch('/voicemail-boxes/{voicemailBox}/messages', [VoicemailMessageController::class, 'bulkUpdate']);
            Route::patch('/voicemail-boxes/{voicemailBox}/messages/{message}', [VoicemailMessageController::class, 'update']);
            Route::get('/voicemail-boxes/{voicemailBox}/messages/{message}/audio', [VoicemailMessageController::class, 'audio']);
            Route::post('/voicemail-boxes/{voicemailBox}/greeting', [VoicemailGreetingController::class, 'store']);
            Route::get('/voicemail-boxes/{voicemailBox}/greeting/audio', [VoicemailGreetingController::class, 'audio']);
            Route::delete('/voicemail-boxes/{voicemailBox}/greeting', [VoicemailGreetingController::class, 'destroy']);
            Route::post('/sync/extensions', [ExtensionSyncController::class, 'store']);
            Route::get('/sync/extensions/{run}', [ExtensionSyncController::class, 'show']);
        });
    });
});
