<?php

use App\Domains\CallDetailRecords\Controllers\CallDetailRecordController;
use App\Domains\Blacklists\Controllers\BlacklistController;
use App\Domains\Blacklists\Controllers\BlacklistSyncController;
use App\Domains\CallDetailRecords\Controllers\CallDetailRecordSyncController;
use App\Domains\CallRouting\Controllers\CallflowController;
use App\Domains\Conferences\Controllers\ConferenceController;
use App\Domains\Conferences\Controllers\ConferenceSyncController;
use App\Domains\Devices\Controllers\DeviceController;
use App\Domains\Directories\Controllers\DirectoryController;
use App\Domains\Directories\Controllers\DirectorySyncController;
use App\Domains\Extensions\Controllers\ExtensionController;
use App\Domains\Extensions\Controllers\ExtensionDetailController;
use App\Domains\Extensions\Controllers\ExtensionRecoveryController;
use App\Domains\Faxes\Controllers\FaxBoxController;
use App\Domains\Faxes\Controllers\FaxController;
use App\Domains\Faxes\Controllers\FaxDocumentController;
use App\Domains\Faxes\Controllers\FaxSyncController;
use App\Domains\Groups\Controllers\GroupController;
use App\Domains\Groups\Controllers\GroupSyncController;
use App\Domains\IdentityAccess\Controllers\SessionController;
use App\Domains\Media\Controllers\MediaAudioController;
use App\Domains\Media\Controllers\MediaController;
use App\Domains\Media\Controllers\MediaSyncController;
use App\Domains\Media\Controllers\MusicOnHoldController;
use App\Domains\Menus\Controllers\MenuController;
use App\Domains\Menus\Controllers\MenuSyncController;
use App\Domains\Organizations\Controllers\AccountController;
use App\Domains\PhoneNumbers\Controllers\PhoneNumberController;
use App\Domains\PhoneNumbers\Controllers\PhoneNumberSyncController;
use App\Domains\Queues\Controllers\AgentController;
use App\Domains\Queues\Controllers\QueueController;
use App\Domains\Queues\Controllers\QueueSyncController;
use App\Domains\Recordings\Controllers\RecordingAudioController;
use App\Domains\Recordings\Controllers\RecordingController;
use App\Domains\Recordings\Controllers\RecordingSyncController;
use App\Domains\Services\Controllers\ServiceOverviewController;
use App\Domains\Services\Controllers\ServiceSyncController;
use App\Domains\SwitchSynchronization\Controllers\ExtensionSyncController;
use App\Domains\TemporalRouting\Controllers\TemporalRoutingSyncController;
use App\Domains\TemporalRouting\Controllers\TemporalRuleController;
use App\Domains\TemporalRouting\Controllers\TemporalRuleSetController;
use App\Domains\Voicemail\Controllers\VoicemailBoxController;
use App\Domains\Voicemail\Controllers\VoicemailGreetingController;
use App\Domains\Voicemail\Controllers\VoicemailMessageController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::get('/health', fn () => response()->json([
        'data' => [
            'service' => 'grid-api',
            'status' => 'healthy',
            'timestamp' => now()->toIso8601String(),
        ],
    ]));

    Route::middleware('auth:sanctum')->group(function (): void {
        Route::get('/session', [SessionController::class, 'show']);
        Route::get('/accounts', AccountController::class);
        Route::get('/accounts/{account}/extensions', ExtensionController::class);
        Route::post('/accounts/{account}/extensions', [ExtensionController::class, 'store']);
        Route::get('/accounts/{account}/extensions/{extension}', ExtensionDetailController::class);
        Route::put('/accounts/{account}/extensions/{extension}', [ExtensionController::class, 'update']);
        Route::get('/accounts/{account}/extensions/{extension}/deletion-preview', [ExtensionController::class, 'deletionPreview']);
        Route::delete('/accounts/{account}/extensions/{extension}', [ExtensionController::class, 'destroy']);
        Route::get('/accounts/{account}/extension-recovery', [ExtensionRecoveryController::class, 'index']);
        Route::post('/accounts/{account}/extension-recovery/{operation}', [ExtensionRecoveryController::class, 'recover']);
        Route::get('/accounts/{account}/devices', [DeviceController::class, 'index']);
        Route::post('/accounts/{account}/devices', [DeviceController::class, 'store']);
        Route::get('/accounts/{account}/devices/{device}', [DeviceController::class, 'show']);
        Route::put('/accounts/{account}/devices/{device}', [DeviceController::class, 'update']);
        Route::delete('/accounts/{account}/devices/{device}', [DeviceController::class, 'destroy']);
        Route::get('/accounts/{account}/directories', [DirectoryController::class, 'index']);
        Route::get('/accounts/{account}/directories/options', [DirectoryController::class, 'options']);
        Route::post('/accounts/{account}/directories', [DirectoryController::class, 'store']);
        Route::get('/accounts/{account}/directories/{directory}', [DirectoryController::class, 'show']);
        Route::put('/accounts/{account}/directories/{directory}', [DirectoryController::class, 'update']);
        Route::delete('/accounts/{account}/directories/{directory}', [DirectoryController::class, 'destroy']);
        Route::post('/accounts/{account}/sync/directories', [DirectorySyncController::class, 'store']);
        Route::get('/accounts/{account}/sync/directories/{run}', [DirectorySyncController::class, 'show']);
        Route::get('/accounts/{account}/groups', [GroupController::class, 'index']);
        Route::get('/accounts/{account}/groups/options', [GroupController::class, 'options']);
        Route::post('/accounts/{account}/groups', [GroupController::class, 'store']);
        Route::get('/accounts/{account}/groups/{group}', [GroupController::class, 'show']);
        Route::put('/accounts/{account}/groups/{group}', [GroupController::class, 'update']);
        Route::delete('/accounts/{account}/groups/{group}', [GroupController::class, 'destroy']);
        Route::post('/accounts/{account}/sync/groups', [GroupSyncController::class, 'store']);
        Route::get('/accounts/{account}/sync/groups/{run}', [GroupSyncController::class, 'show']);
        Route::get('/accounts/{account}/queues', [QueueController::class, 'index']);
        Route::get('/accounts/{account}/queues/options', [QueueController::class, 'options']);
        Route::post('/accounts/{account}/queues', [QueueController::class, 'store']);
        Route::get('/accounts/{account}/queues/{queue}', [QueueController::class, 'show']);
        Route::put('/accounts/{account}/queues/{queue}', [QueueController::class, 'update']);
        Route::delete('/accounts/{account}/queues/{queue}', [QueueController::class, 'destroy']);
        Route::get('/accounts/{account}/agents', [AgentController::class, 'index']);
        Route::get('/accounts/{account}/agents/{agent}/status', [AgentController::class, 'status']);
        Route::post('/accounts/{account}/agents/{agent}/status', [AgentController::class, 'updateStatus']);
        Route::post('/accounts/{account}/sync/queues', [QueueSyncController::class, 'store']);
        Route::get('/accounts/{account}/sync/queues/{run}', [QueueSyncController::class, 'show']);
        Route::get('/accounts/{account}/menus', [MenuController::class, 'index']);
        Route::get('/accounts/{account}/blacklists', [BlacklistController::class, 'index']);
        Route::post('/accounts/{account}/blacklists', [BlacklistController::class, 'store']);
        Route::get('/accounts/{account}/blacklists/{blacklist}', [BlacklistController::class, 'show']);
        Route::put('/accounts/{account}/blacklists/{blacklist}', [BlacklistController::class, 'update']);
        Route::delete('/accounts/{account}/blacklists/{blacklist}', [BlacklistController::class, 'destroy']);
        Route::post('/accounts/{account}/sync/blacklists', [BlacklistSyncController::class, 'store']);
        Route::get('/accounts/{account}/sync/blacklists/{run}', [BlacklistSyncController::class, 'show']);
        Route::get('/accounts/{account}/menus/options', [MenuController::class, 'options']);
        Route::post('/accounts/{account}/menus', [MenuController::class, 'store']);
        Route::get('/accounts/{account}/menus/{menu}', [MenuController::class, 'show']);
        Route::put('/accounts/{account}/menus/{menu}', [MenuController::class, 'update']);
        Route::delete('/accounts/{account}/menus/{menu}', [MenuController::class, 'destroy']);
        Route::post('/accounts/{account}/sync/menus', [MenuSyncController::class, 'store']);
        Route::get('/accounts/{account}/sync/menus/{run}', [MenuSyncController::class, 'show']);
        Route::get('/accounts/{account}/temporal-rules', [TemporalRuleController::class, 'index']);
        Route::post('/accounts/{account}/temporal-rules', [TemporalRuleController::class, 'store']);
        Route::get('/accounts/{account}/temporal-rules/{rule}', [TemporalRuleController::class, 'show']);
        Route::put('/accounts/{account}/temporal-rules/{rule}', [TemporalRuleController::class, 'update']);
        Route::delete('/accounts/{account}/temporal-rules/{rule}', [TemporalRuleController::class, 'destroy']);
        Route::get('/accounts/{account}/temporal-rule-sets', [TemporalRuleSetController::class, 'index']);
        Route::get('/accounts/{account}/temporal-rule-sets/options', [TemporalRuleSetController::class, 'options']);
        Route::post('/accounts/{account}/temporal-rule-sets', [TemporalRuleSetController::class, 'store']);
        Route::get('/accounts/{account}/temporal-rule-sets/{set}', [TemporalRuleSetController::class, 'show']);
        Route::put('/accounts/{account}/temporal-rule-sets/{set}', [TemporalRuleSetController::class, 'update']);
        Route::delete('/accounts/{account}/temporal-rule-sets/{set}', [TemporalRuleSetController::class, 'destroy']);
        Route::post('/accounts/{account}/sync/temporal-routing', [TemporalRoutingSyncController::class, 'store']);
        Route::get('/accounts/{account}/sync/temporal-routing/{run}', [TemporalRoutingSyncController::class, 'show']);
        Route::get('/accounts/{account}/phone-numbers', [PhoneNumberController::class, 'index']);
        Route::get('/accounts/{account}/phone-numbers/{phoneNumber}', [PhoneNumberController::class, 'show']);
        Route::get('/accounts/{account}/callflows', [CallflowController::class, 'index']);
        Route::get('/accounts/{account}/callflows/editor', [CallflowController::class, 'createOptions']);
        Route::post('/accounts/{account}/callflows', [CallflowController::class, 'store']);
        Route::get('/accounts/{account}/callflows/{callflow}/editor', [CallflowController::class, 'edit']);
        Route::get('/accounts/{account}/callflows/{callflow}', [CallflowController::class, 'show']);
        Route::put('/accounts/{account}/callflows/{callflow}', [CallflowController::class, 'update']);
        Route::delete('/accounts/{account}/callflows/{callflow}', [CallflowController::class, 'destroy']);
        Route::get('/accounts/{account}/call-detail-records', [CallDetailRecordController::class, 'index']);
        Route::get('/accounts/{account}/call-detail-records/{callDetailRecord}', [CallDetailRecordController::class, 'show']);
        Route::get('/accounts/{account}/recordings', [RecordingController::class, 'index']);
        Route::get('/accounts/{account}/recordings/{recording}', [RecordingController::class, 'show']);
        Route::get('/accounts/{account}/recordings/{recording}/audio', [RecordingAudioController::class, 'show']);
        Route::post('/accounts/{account}/sync/recordings', [RecordingSyncController::class, 'store']);
        Route::get('/accounts/{account}/sync/recordings/{run}', [RecordingSyncController::class, 'show']);
        Route::get('/accounts/{account}/conferences', [ConferenceController::class, 'index']);
        Route::get('/accounts/{account}/conferences/options', [ConferenceController::class, 'options']);
        Route::post('/accounts/{account}/conferences', [ConferenceController::class, 'store']);
        Route::get('/accounts/{account}/conferences/{conference}', [ConferenceController::class, 'show']);
        Route::put('/accounts/{account}/conferences/{conference}', [ConferenceController::class, 'update']);
        Route::delete('/accounts/{account}/conferences/{conference}', [ConferenceController::class, 'destroy']);
        Route::post('/accounts/{account}/sync/conferences', [ConferenceSyncController::class, 'store']);
        Route::get('/accounts/{account}/sync/conferences/{run}', [ConferenceSyncController::class, 'show']);
        Route::get('/accounts/{account}/fax-boxes', [FaxBoxController::class, 'index']);
        Route::get('/accounts/{account}/fax-boxes/options', [FaxBoxController::class, 'options']);
        Route::post('/accounts/{account}/fax-boxes', [FaxBoxController::class, 'store']);
        Route::get('/accounts/{account}/fax-boxes/{faxBox}', [FaxBoxController::class, 'show']);
        Route::put('/accounts/{account}/fax-boxes/{faxBox}', [FaxBoxController::class, 'update']);
        Route::delete('/accounts/{account}/fax-boxes/{faxBox}', [FaxBoxController::class, 'destroy']);
        Route::get('/accounts/{account}/faxes', [FaxController::class, 'index']);
        Route::get('/accounts/{account}/faxes/{fax}', [FaxController::class, 'show']);
        Route::get('/accounts/{account}/faxes/{fax}/document', [FaxDocumentController::class, 'show']);
        Route::post('/accounts/{account}/sync/faxes', [FaxSyncController::class, 'store']);
        Route::get('/accounts/{account}/sync/faxes/{run}', [FaxSyncController::class, 'show']);
        Route::get('/accounts/{account}/services', [ServiceOverviewController::class, 'show']);
        Route::post('/accounts/{account}/sync/services', [ServiceSyncController::class, 'store']);
        Route::get('/accounts/{account}/sync/services/{run}', [ServiceSyncController::class, 'show']);
        Route::get('/accounts/{account}/media', [MediaController::class, 'index']);
        Route::post('/accounts/{account}/media', [MediaController::class, 'store']);
        Route::get('/accounts/{account}/media/music-on-hold', [MusicOnHoldController::class, 'show']);
        Route::put('/accounts/{account}/media/music-on-hold', [MusicOnHoldController::class, 'update']);
        Route::get('/accounts/{account}/media/{media}', [MediaController::class, 'show']);
        Route::put('/accounts/{account}/media/{media}', [MediaController::class, 'update']);
        Route::delete('/accounts/{account}/media/{media}', [MediaController::class, 'destroy']);
        Route::get('/accounts/{account}/media/{media}/audio', [MediaAudioController::class, 'show']);
        Route::post('/accounts/{account}/media/{media}/audio', [MediaAudioController::class, 'store']);
        Route::post('/accounts/{account}/sync/media', [MediaSyncController::class, 'store']);
        Route::get('/accounts/{account}/sync/media/{run}', [MediaSyncController::class, 'show']);
        Route::post('/accounts/{account}/sync/call-detail-records', [CallDetailRecordSyncController::class, 'store']);
        Route::get('/accounts/{account}/sync/call-detail-records/{run}', [CallDetailRecordSyncController::class, 'show']);
        Route::post('/accounts/{account}/sync/phone-numbers', [PhoneNumberSyncController::class, 'store']);
        Route::get('/accounts/{account}/sync/phone-numbers/{run}', [PhoneNumberSyncController::class, 'show']);
        Route::get('/accounts/{account}/voicemail-boxes', [VoicemailBoxController::class, 'index']);
        Route::post('/accounts/{account}/voicemail-boxes', [VoicemailBoxController::class, 'store']);
        Route::get('/accounts/{account}/voicemail-boxes/{voicemailBox}', [VoicemailBoxController::class, 'show']);
        Route::put('/accounts/{account}/voicemail-boxes/{voicemailBox}', [VoicemailBoxController::class, 'update']);
        Route::delete('/accounts/{account}/voicemail-boxes/{voicemailBox}', [VoicemailBoxController::class, 'destroy']);
        Route::get('/accounts/{account}/voicemail-boxes/{voicemailBox}/messages', [VoicemailMessageController::class, 'index']);
        Route::patch('/accounts/{account}/voicemail-boxes/{voicemailBox}/messages', [VoicemailMessageController::class, 'bulkUpdate']);
        Route::patch('/accounts/{account}/voicemail-boxes/{voicemailBox}/messages/{message}', [VoicemailMessageController::class, 'update']);
        Route::get('/accounts/{account}/voicemail-boxes/{voicemailBox}/messages/{message}/audio', [VoicemailMessageController::class, 'audio']);
        Route::post('/accounts/{account}/voicemail-boxes/{voicemailBox}/greeting', [VoicemailGreetingController::class, 'store']);
        Route::get('/accounts/{account}/voicemail-boxes/{voicemailBox}/greeting/audio', [VoicemailGreetingController::class, 'audio']);
        Route::delete('/accounts/{account}/voicemail-boxes/{voicemailBox}/greeting', [VoicemailGreetingController::class, 'destroy']);
        Route::post('/accounts/{account}/sync/extensions', [ExtensionSyncController::class, 'store']);
        Route::get('/accounts/{account}/sync/extensions/{run}', [ExtensionSyncController::class, 'show']);
    });
});
